name: CI

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  lint:
    runs-on: ubuntu-26.04
    name: Lint
    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0
          bundler-cache: true
      - name: Run RuboCop
        run: bundle exec rubocop lib spec

  gem-test:
    runs-on: ubuntu-26.04
    name: Gem Tests (Ruby ${{ matrix.ruby }})
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.4"
          - "4.0"

    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run specs
        run: bundle exec rspec

  docs-lint:
    runs-on: ubuntu-26.04
    name: Docs Lint
    defaults:
      run:
        working-directory: docs

    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0
          bundler-cache: true
          working-directory: docs
      - name: Run RuboCop
        run: bundle exec rubocop

  docs-test:
    runs-on: ubuntu-26.04
    name: Docs Tests
    defaults:
      run:
        working-directory: docs

    steps:
      - uses: actions/checkout@v7
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0
          bundler-cache: true
          working-directory: docs
      - name: Run specs
        run: bundle exec rspec
